info:
  contact: {}
paths:
  /create-staff:
    post:
      consumes:
      - application/json
      description: create a new staff account
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Create a new staff account
swagger: "2.0"
